version: '3.8'

services:
  api:
    build: .
    image: searchai-api
    container_name: searchai-api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/src/app
    env_file:
      - .env
    restart: unless-stopped